### PR TITLE
don't parse addresses with invalid domains

### PR DESCRIPTION
**Pull request by hengwoon**
Per RFC 2822, domains like ".domain.com" or "domain..com" are not valid.

```
# RFC 2822
dot-atom        =       [CFWS] dot-atom-text [CFWS]
dot-atom-text   =       1*atext *("." 1*atext)
```

Domains should be a domain_text element followed by zero or more
domain_text elements prefixed with "."

### CODE REVIEW

**Comment by kennethkalmer** [comment]
:+1: on this!

**Comment by bpot** [comment]
:+1: nice catch! I can't remember any reason why this deviated from the spec.

**Comment by bf4** [comment]
@jeremy ok to merge?

**Comment by jeremy** [comment]
Previously reported in #279 as a deviation from RFC, patched in #286, and reverted in #397. These deviations are not-uncommonly seen in the wild, so we purposefully support parsing them.

**Pull request closed without merging**
