### PR TITLE
Handle unknown b-value encoding

### PR DESCRIPTION
**Pull request by kjg**
by treating it as ascii as well as ignoring any invalid chars

### CODE REVIEW

**Comment by kjg** [comment]
Quick question: How would you feel about replacing invalid chars with `"�"` instead of `""`. That way it is clear that something went "wrong" during translation where we otherwise just pretend everything was okay with no notice.

**Comment by jeremy** [comment]
Good call on � 👍

**Comment by kjg** [comment]
Should I change that in this PR or a new one?

Any idea offhand how to get Iconv to do � in 1.8.7?

If it isn’t easy / built in to Iconv, is it worth it to add for 1.8.7, or should I do it just for the String#encode versions?


On March 31, 2016 at 11:15:25 AM, Jeremy Daer (notifications@github.com) wrote:

Good call on � 👍

**Comment by kjg** [comment]
Yeah, as far as I can tell, There is no good way to specify a replacement character in 1.8.7. Any 1.8.7 solution that I can think of to replace invalid characters would involve iterating over bytes and be really messy.

So the question becomes do we scrap � and leave the replacement as "" across the board, or do we allow the 1.8.7 output to be different.

I vote for allowing the 1.8.7 output to be slightly different.

**Comment by bf4** [comment]
@kjg Maybe https://github.com/bf4/encoded_string/blob/master/lib/encoded_string.rb#L14-L19 helps? I don't have 1.8.7 to test

**Comment by jeremy** [comment]
Separate PR makes sense.

**Comment by kjg** [comment]
This is passing now after a rebase. I'll make the replacement character change in a separate PR

**Pull request merged**
