### PR TITLE
autoload parsers for load-time speed and memory usage

### PR DESCRIPTION
**Pull request by grosser**
https://github.com/mikel/mail/issues/812

@bf4 
### Risks
- None

### CODE REVIEW

**Comment by tenderlove** [comment]
If this doesn't load parsers until runtime, and my app needs the parser, does that mean that the lazy loading will ruin CoW advantages of eager loading?  I mean, should people who use the parser and forking severs know that they should eagerly load?  (Otherwise this could possibly increase memory usage)

**Comment by SamSaffron** [comment]
aren't we usually doing mail parsing in sidekiqs anyway?

**Comment by grosser** [comment]
Yes balancing dev vs production needs is always problematic,
in rails you should use eager_load in production and maybe something
similar in other frameworks.

We do mail parsing in resque with forks.

**Comment by tenderlove** [comment]
> in rails you should use eager_load in production and maybe something
> similar in other frameworks.

`eager_load` doesn't guarantee that the mail parser constant will be touched (e.g. the first time the constant is referenced could be in a method that isn't executed until runtime). :-/

**Comment by grosser** [comment]
but adding it to eager_load_paths would do the trick ?

**Pull request closed without merging**
