### PR TITLE
Feature/allow blank in smtp_envelope_from

### PR DESCRIPTION
**Pull request by kirikak2**
see #889

### CODE REVIEW

**Comment by jeremy** [comment]
+1 to allow blank SMTP `MAIL FROM`. Could you update the specs?

**Comment by kirikak2** [comment]
Thank you for your response.
Ofcourse. I'll update specs soon.

**Comment by kirikak2** [comment]
@jeremy It ready to merge.

**Comment by jeremy** [comment]
Thanks @kirikak2. This flipped all the tests to say "doesn't raise an exception." Rather than testing that we don't raise an error, let's test the expected results. What happens when we send a message with no SMTP envelope From?

**Comment by jeremy** [comment]
Rather than omit the envelope From address entirely, we can provide a null sender explicitly:
```ruby
smtp_envelope_from Mail::Constants::NULL_SENDER

# or
smtp_envelope_from '<>'
```

See #745

**Pull request closed without merging**
