### PR TITLE
refactor: Use Ruby 2's __dir__ where possible

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR introduces more usage of the [`__dir__`](https://www.rubydoc.info/stdlib/core/Kernel:__dir__) method.

### CODE REVIEW

**Comment by mikel** [comment]
Thanks, nice improvement, please add a changelog and I'll merge it.

**Comment by mikel** [comment]
Sorry, we have some conflicts now due to another PR, please fix and I'll get merged.

**Comment by olleolleolle** [comment]
@mikel There!

**Comment by mikel** [comment]
Perfect :)

**Pull request merged**
