### PR TITLE
Bugfix/pop3 frozen string

### PR DESCRIPTION
**Pull request by Eraden**
Hi mikel :wave: 

I tried to use you library with ruby 2.5.0 and 2.6.0-preview1 and I had Froze String Exception.
So I digged a little bit and I found this is because appending mail body to pure string.
So I replaced it with `StringIO` and it started to working properly.

### CODE REVIEW

**Comment by jeremy** [comment]
Hey @Eraden, thanks for the report! This is a Ruby bug that'll be fixed in 2.5.1 and 2.6.0-preview2: https://bugs.ruby-lang.org/issues/14416. See #1209.

**Comment by cantino** [comment]
I'm using 2.5.1 and am still having this issue. Is there any easy fix?

**Comment by jeremy** [comment]
Sounds like you have a different issue then @cantino. Crack open a debugger and track it down!

**Comment by zealot128** [comment]
Seems to be the same issue. That fix is not included in the latest Ruby 2.5.1

```
RUBY_DESCRIPTION
=> "ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]"

Mail.all
FrozenError: can't modify frozen String
from /home/local/PDC01/swi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/pop.rb:808:in `block in pop'

-->

Exception: FrozenError: can't modify frozen String
--
0: /home/local/PDC01/swi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/pop.rb:808:in `block in pop'
1: /home/local/PDC01/swi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:276:in `each_message_chunk'
2: /home/local/PDC01/swi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/pop.rb:955:in `block in retr'
3: /home/local/PDC01/swi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/pop.rb:1013:in `critical'
4: /home/local/PDC01/swi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/pop.rb:953:in `retr'                                                                                                                             5: /home/local/PDC01/swi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/pop.rb:807:in `pop'
6: /home/local/PDC01/swi/.rvm/gems/ruby-2.5.1/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:84:in `block (2 levels) in find'
7: /home/local/PDC01/swi/.rvm/gems/ruby-2.5.1/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:83:in `each'
8: /home/local/PDC01/swi/.rvm/gems/ruby-2.5.1/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:83:in `block in find'
9: /home/local/PDC01/swi/.rvm/gems/ruby-2.5.1/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:135:in `start'
```

So currently, Receiving Mails via POP is not possible in any released Ruby 2.5.x version.

**Pull request closed without merging**
