### PR TITLE
Update mime types dependency

### PR DESCRIPTION
**Pull request by beanieboi**
hey,

2nd attempt to fix the missing pieces from #928 
let me know if there are any other issues to fix, i can contribute time to make this work.

thanks
ben

### CODE REVIEW

**Comment by bf4** [comment]
Looks good to me @halostatue @jeremy ?

**Comment by jodosha** [comment]
:+1: :100: :heart: Thanks @beanieboi !

**Comment by karlfreeman** [comment]
Was just looking into doing this myself. `mail` is the only dependency which is pinning `mime-types` to not take advantage of some memory improvements that come with `~ 3.0` (https://github.com/rubygems/rubygems.org/pull/1172). :+1: :smiley:.

**Comment by halostatue** [comment]
This looks good to me. Thanks, @beanieboi for following this through.

**Comment by nateberkopec** [comment]
:tada: Woop woop!

**Comment by bf4** [comment]
@jeremy Can we release this?

**Comment by beanieboi** [comment]
yay! thanks everybody!

**Comment by karlfreeman** [comment]
:tada: :+1: :tada:

**Comment by jeremy** [comment]
@bf4 I'll cut an rc2 gem today 🤘

**Comment by bf4** [comment]
:fireworks:

**Comment by jeremy** [comment]
Pushed 2.6.4.rc2 – give it a shot! https://rubygems.org/gems/mail

**Comment by jodosha** [comment]
@jeremy Thank you. I've got a problem with this rc2 release:

This [test](https://github.com/lotus/mailer/blob/master/test/delivery_test.rb#L50) fails:

```shell
  1) Failure:
Lotus::Mailer::.deliver::test delivery with hardcoded values#test_0004_interprets the prepare statement [/Users/luca/Code/lotus/mailer/test/delivery_test.rb:60]:
--- expected
+++ actual
@@ -1 +1 @@
-"application/pdf; charset=UTF-8; filename=invoice.pdf"
+"application/pdf; filename=invoice.pdf"
```

The charset is missing, it's probably because `mime-types` bumped to 3.0, so this could be a breaking change from their side.

---

I can easily fix on my side, just wanted you to be aware of this. Cheers.

**Comment by halostatue** [comment]
@jodosha: This is definitely not because of `mime-types` as the library does not currently do anything at all with `Content-Type` attribute parsing. (`mime-types` currently works below the level of HTTP content type handling; this is something I am looking at integrating in the future for type attributing, but it isn’t there because I don’t have an API that I like yet.)

**Comment by beanieboi** [comment]
@jeremy awesome! thank you!

**Comment by jodosha** [comment]
@halostatue Thanks for letting me know! Thank you for `mime-types`, btw!! :+1:

**Comment by ioquatix** [comment]
Are we ready to release 2.6.4?

**Pull request merged**
