### PR TITLE
Fix bug IMAP delete_all method

### PR DESCRIPTION
**Pull request by kimromi**
An error occurred when called `delete_all` of IMAP.

```
Net::IMAP::NoResponseError: Cannot expunge read-only mailbox.
```

`imap.examine` is readonly, so I fixed to `imap.select`

### CODE REVIEW

**Comment by kimromi** [comment]
please review!

**Comment by kimromi** [comment]
@jeremy Are there any mistakes in this contribution? 😢

**Comment by jeremy** [comment]
Squashed @ 6bc16b4bce4fe280b19523c939b14a30e32a8ba4 and backported to 2-7-stable at 19592c0555c699ba8d54bccd3b31483d1aff0692.

**Comment by kimromi** [comment]
@jeremy Thank you!!😄

**Pull request closed without merging**
