### PR TITLE
[travis] add truffleruby

### PR DESCRIPTION
**Pull request by ahorek**
separated from https://github.com/mikel/mail/pull/1303

### CODE REVIEW

**Comment by jeremy** [comment]
Pending Travis + rvm gpg issue.

**Comment by ahorek** [comment]
rb-inotify has the same issue https://travis-ci.org/guard/rb-inotify/builds/468526922?utm_source=github_status&utm_medium=notification

hopefully it'll be fixed soon

**Comment by jeremy** [comment]
References https://github.com/travis-ci/travis-build/pull/1604

**Comment by jeremy** [comment]
Caused by https://github.com/rvm/rvm/issues/4520. RVM maintainers switched personal signing keys.

**Comment by jeremy** [comment]
Merging in anticipation of Travis adding the new RVM signing key.

**Comment by ahorek** [comment]
thanks for investigation

**Pull request merged**
