### PR TITLE
add `an_attachment_with_mime_type` option to check mime_type of attachments

### PR DESCRIPTION
**Pull request by tansaku**
thought this would be useful.

I have been following the contribution instructions as far as I can

> Tell me you have tested it against more than one version of Ruby, RVM is great for this. I test against 7 rubies before I push into master.

I tried to test against rubies 1.8.7 and 1.9.3 but was stuck on:

```
→ gem install bundler:2.0.2
Fetching: bundler-2.0.2.gem (100%)
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.3.0.
```
all specs pass for ruby 2.6.5 and ruby 2.5.0  

I could not install dependencies for anything less than ruby 2.5.0 due to issues like the folllowing:

```
byebug-11.1.1 requires ruby version >= 2.4.0, which is incompatible with the current version, ruby 2.3.0p0
```

```
rufo-0.11.0 requires ruby version >= 2.4.5, which is incompatible with the current version, ruby 2.4.0p0
```

> Use good, idiomatic, structured and modular code

I copied the existing format precisely

> Include tests that fail without your code, and pass with it

have double checked that they fail appropriately

> Update the documentation, the surrounding one, examples elsewhere, guides, whatever is affected by your contribution

Have updated the README and CHANGELOG

### CODE REVIEW

**Comment by tansaku** [comment]
for those waiting for this to be merged and who don't want to link to my repo the following helper patch can be used to achieve the same effect:

```
module Mail
  module Matchers
    def an_attachment_with_mime_type(filename)
      AttachmentMimeTypeMatcher.new(filename)
    end

    class AttachmentMimeTypeMatcher
      attr_reader :mime_type
      def initialize(mime_type)
        @mime_type = mime_type
      end

      def ===(other)
        other.attachment? && other.mime_type == mime_type
      end
    end
  end
end
```

**Comment by jeremy** [comment]
Thanks @tansaku !

**Comment by tansaku** [comment]
you're most welcome - I have a few more minor fix up changes if you've interested

**Comment by tansaku** [comment]
btw, what's the time frame for this to be released with the next update of the gem>

**Comment by jeremy** [comment]
Weeks to months for next minor and major releases. Bundling from git is a good choice in the meantime.

Please do contribute your fix up changes!

**Pull request merged**
