### PR TITLE
do not lie about the strings encoding

### PR DESCRIPTION
**Pull request by james-lawrence**
one possible way to address https://github.com/mikel/mail/issues/902
this is more of pointing out the issue further than an actual proposed fix.

### CODE REVIEW

**Comment by jeremy** [comment]
Think this is a good idea. Pragmatic choice.

**Comment by bf4** [comment]
:+1: Meanwhile, in terms of a fix, I covered all encoding cases in rspec-support

- https://github.com/rspec/rspec-support/blob/81e33d4ed3/lib/rspec/support/encoded_string.rb
- https://github.com/rspec/rspec-support/blob/81e33d4ed3/spec/rspec/support/encoded_string_spec.rb

Perhaps we/I should extract parts of that

**Comment by james-lawrence** [comment]
have some further tests/fixes. this code is broken when emails contain array header fields with multiple encodings. the gsub fails and blows up wonderfully if a string is say utf-7 encoded.

**Comment by james-lawrence** [comment]
further investigation leads me to say that the multiple encodings isn't a problem unless ruby can't correctly decode once of the encoding, at which point it should blow up.

**Comment by bf4** [comment]
Extracted https://github.com/bf4/encoded_string with rspec's blessing.. It's well-tested, but I haven't done much with it on its own. Feel free to try it out

**Comment by james-lawrence** [comment]
dead pr.

**Pull request closed without merging**
