### PR TITLE
Download spam corpus and verify all in a script

### PR DESCRIPTION
**Pull request by bf4**
For consideration

### CODE REVIEW

**Comment by bf4** [comment]
@mikel @jeremy any objections?

**Comment by jeremy** [comment]
What's your thinking here @bf4 ? Can see this is making it easier to download the spam corpus, but not sure about the significance of introducing the test script.

If it were for convenience alone, I'd expect a couple of new rake tasks, e.g. `corpus:spam:download` and `corpus:spam:verify`

**Comment by bf4** [comment]
I suppose I could see about moving the code from bash to Ruby.

My thinking is basically just to make it easier to run the test.

**Comment by bf4** [comment]
Also, it was part of my interest in writing up a 'how to release mail' that I wanted to extract from @mikel  :)

**Comment by jeremy** [comment]
Cool. Using rake tasks means you can represent the dependencies that'd otherwise need imperative code (like whether to download, how to unpack, etc). Makefile!

**Comment by bf4** [comment]
I rebased off of master and started converting the script to ruby/rake... sharing it here just in case you want to look at it between now and when I come back to this.

**Comment by jeremy** [comment]
Closing this out until we wrap it up. Moved the branch off this origin, reserved for release branches, and pushed an update to https://github.com/jeremy/mail/tree/verify_corpus 👍

**Pull request closed without merging**
