### PR TITLE
Fix nil message_encoding when message_encoding is ""

### PR DESCRIPTION
**Pull request by jakubonty**

### CODE REVIEW

**Comment by jeremy** [comment]
Backported to 2-7-stable @ 34aef0dc7a3e7ff26aea7267f137887ea04a9a19

**Comment by alyssais** [comment]
Hey! Is there a release of 2-7-stable planned any time soon? Anything I could do to help make that happen? :)

**Comment by jeremy** [comment]
Soon, yes. (I've been hoping to get to the bottom of line ending normalization, but it's a toughie and I'll probably punt to 2.7.2.)

**Comment by arashm** [comment]
A release would really help us too.

**Pull request closed without merging**
