### PR TITLE
Cache the expensive only_us_ascii? check

### PR DESCRIPTION
**Pull request by dalibor**
Is this safe to do?

In my benchmarks I'm seeing from 15-20% speed improvement when building emails with a 40KB html part and 30-40% speed improvement when building emails with large attachments.

### CODE REVIEW

**Comment by dalibor** [comment]
@jeremy Great using `String#ascii_only?`! The only difference is that the original regex excludes `"\x00"` while `ascii_only?` includes it, does it matter? With this change the test suite time goes from 2.3 seconds to 1.6 seconds. And also, I'm seeing significant performance improvements in benchmarks locally building real emails.

```
30 attachments of ~ 10MB each:   17.801965 sec -> 5.149144 sec (~ 3x faster)
10000 html parts of ~ 40KB each: 16.148903 sec -> 9.189533 sec (~ 1x faster)
```

**Comment by jeremy** [comment]
IMO that was a bug, since we don't want NUL bytes in our US-ASCII text either :)

Very nice improvements!

**Comment by dalibor** [comment]
It's the other way around, the new `ascii_only?` check will allow NUL bytes in emails I'm afraid. :) If we want to prevent that, we could do `raw_source.ascii_only? && raw_source !~ /\x00/` :/, but that would be slower than `ascii_only?` and faster than the original regex.

**Comment by jeremy** [comment]
Hmm yes. This seems like an implementation wart, really. NUL is legit for US-ASCII. It's not legal in emails, but that's not what we're validating here, so we can get away with the `ascii_only?`check.

**Comment by dalibor** [comment]
Great, thanks for checking that, Jeremy.

**Pull request closed without merging**
